export const ICAO_COUNTRY = {
  K:'United States',    P:'United States',    C:'Canada',
  M:'Mexico',           T:'Caribbean',        S:'South America',
  EG:'United Kingdom',  EI:'Ireland',
  ED:'Germany',         ET:'Germany',
  LF:'France',
  LE:'Spain',           LP:'Portugal',
  LI:'Italy',
  EH:'Netherlands',     EB:'Belgium',
  EP:'Poland',          LO:'Austria',
  LK:'Czech Republic',  LZ:'Slovakia',
  LH:'Hungary',         LB:'Bulgaria',
  LD:'Croatia',         LG:'Greece',          LC:'Cyprus',
  LT:'Turkey',
  ES:'Sweden',          EN:'Norway',
  EF:'Finland',         EK:'Denmark',
  EV:'Latvia',          EY:'Lithuania',       EE:'Estonia',
  UK:'Ukraine',         UU:'Russia',          UL:'Russia',
  UM:'Belarus',         UG:'Georgia',         UB:'Azerbaijan',
  OJ:'Jordan',          OI:'Iran',            OE:'Saudi Arabia',
  OO:'Oman',            OM:'UAE',             OK:'Kuwait',
  OB:'Bahrain',         OQ:'Qatar',
  OP:'Pakistan',        OA:'Afghanistan',
  VI:'India',           VA:'India',           VO:'India',          VG:'India',
  VH:'Australia',       NZ:'New Zealand',
  RK:'South Korea',     RJ:'Japan',
  ZB:'China',           ZG:'China',           ZS:'China',          ZU:'China',
  VT:'Thailand',        VV:'Vietnam',
  WS:'Singapore',       WI:'Indonesia',       WA:'Indonesia',
  VY:'Myanmar',
  FK:'South Africa',    FA:'South Africa',
  HE:'Egypt',           HK:'Kenya',           HA:'Ethiopia',
  DN:'Nigeria',
  SB:'Brazil',          SA:'Argentina',       SK:'Colombia',       SE:'Ecuador',
  SP:'Peru',            SC:'Chile',
};